import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getAuditTrail } from '../utils/storage';
import { useMemo } from 'react';
import { format } from 'date-fns';
import { History, User as UserIcon, Clock } from 'lucide-react';
export default function AuditTrail({ user }) {
    const auditTrail = getAuditTrail();
    const sortedTrail = useMemo(() => {
        return [...auditTrail].sort((a, b) => b.changedAt.getTime() - a.changedAt.getTime());
    }, [auditTrail]);
    return (_jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsxs("h2", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(History, { className: "text-eli-blue", size: 32 }), "Audit Trail"] }), _jsx("p", { className: "text-gray-600 mt-2", children: "Complete record of all system activities and changes" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [_jsxs("div", { className: "card p-6 bg-blue-50", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Total Activities" }), _jsx("p", { className: "text-4xl font-bold text-eli-blue", children: auditTrail.length })] }), _jsxs("div", { className: "card p-6 bg-green-50", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Your Activities" }), _jsx("p", { className: "text-4xl font-bold text-green-600", children: auditTrail.filter((a) => a.changedBy === user.name).length })] }), _jsxs("div", { className: "card p-6 bg-purple-50", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Last Activity" }), _jsx("p", { className: "text-sm font-semibold text-purple-600 mt-3", children: auditTrail.length > 0
                                    ? format(sortedTrail[0].changedAt, 'MMM dd, yyyy HH:mm:ss')
                                    : 'No activities' })] })] }), _jsxs("div", { className: "card p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-6", children: "Activity Timeline" }), sortedTrail.length === 0 ? (_jsxs("div", { className: "text-center py-12", children: [_jsx(Clock, { size: 48, className: "mx-auto text-gray-300 mb-4" }), _jsx("p", { className: "text-gray-600", children: "No audit trail records yet" })] })) : (_jsx("div", { className: "space-y-4", children: sortedTrail.map((entry, index) => (_jsxs("div", { className: "flex gap-4 pb-4 border-b border-gray-200 last:border-0", children: [_jsxs("div", { className: "flex flex-col items-center", children: [_jsx("div", { className: "w-4 h-4 rounded-full bg-eli-blue mt-2" }), index < sortedTrail.length - 1 && _jsx("div", { className: "w-1 h-12 bg-blue-200" })] }), _jsx("div", { className: "flex-1 pt-1", children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-900", children: entry.action }), _jsxs("div", { className: "flex items-center gap-4 mt-2 text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(UserIcon, { size: 16 }), entry.changedBy] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Clock, { size: 16 }), format(entry.changedAt, 'MMM dd, yyyy HH:mm:ss')] })] })] }), _jsxs("div", { className: "text-xs bg-gray-100 px-3 py-1 rounded text-gray-700 font-semibold", children: ["ID: ", entry.recordId] })] }) })] }, entry.id))) }))] }), _jsxs("div", { className: "card p-6 mt-8 bg-gradient-to-r from-eli-light to-blue-50 border-l-4 border-eli-blue", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-3", children: "Audit Trail Compliance" }), _jsxs("ul", { className: "space-y-2 text-sm text-gray-700", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-green-600 font-bold", children: "\u2713" }), " All activities recorded with timestamps"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-green-600 font-bold", children: "\u2713" }), " User attribution tracked for every action"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-green-600 font-bold", children: "\u2713" }), " Records are immutable"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-green-600 font-bold", children: "\u2713" }), " Meets 21 CFR Part 11 requirements"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-green-600 font-bold", children: "\u2713" }), " Full ALCOA+ compliance"] })] })] })] }));
}
